# PiliarSelectorPatch 配置文件

# Sheet名称配置
sheets:
  # 数据总表的Sheet名称
  data_sheet: "总表"
  # 筛选条件的Sheet名称
  filter_sheet: "总表筛选"

# 输出配置
output:
  # 输出目录
  directory: "outputs"
  # 筛选条件前缀
  condition_prefix: "条件_"

# 日志配置
logging:
  # 日志级别: DEBUG, INFO, WARNING, ERROR, CRITICAL
  level: "INFO"
  # 日志格式
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  # 日志文件
  file: "app.log"